[package]
name = "graphql_interfaces"
version = "0.0.1"
edition = "2021"

[workspace]
resolver = "2"
members = ["client", "parser", "server"]

[dependencies]
graphql_client = {path = "./client"}
graphql_server = {path = "./server"}
graphql_parser = {path = "./parser"}
